name: Build, Test and Sonar

on:
  push:
    branches:
      - main
      - "feature/**"
      - "fix/**"

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-test-sonar:
    name: Build, Test and Sonar
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du projet
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # nécessaire pour une analyse Sonar complète

      - name: Installer Java 25
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "25"
          cache: maven

      - name: Autoriser Maven Wrapper
        run: chmod +x mvnw

      - name: Build et tests
        run: ./mvnw clean verify

      - name: Analyse SonarCloud
        if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: >
          ./mvnw sonar:sonar
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=${{ vars.SONAR_ORGANIZATION }}
          -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY }}